/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.belogical.agentactif.model.views;

import com.belogical.agentactif.model.Cellule;
import com.belogical.agentactif.model.Environnement;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.border.EtchedBorder;

/**
 *
 * @author yirou
 */
public class EnvironnementView extends javax.swing.JFrame {

    private Environnement environnement = Environnement.getInstance();
    private List<MyButton> buttons = new ArrayList<>();
    private final Dimension dimension = new Dimension(50, 50);
    public static final String urlAgentExplorateur="src/main/resources/img/androidExplorateur.png";
    public static final String urlAgentEscavateur="src/main/resources/img/agentEscavateur.png";
    public static final String urlAgentTransporteur="src/main/resources/img/androidTranspoteur.png";
    public static final String urlMinerai="src/main/resources/img/diamant.png";
    public static final String urlRocher="src/main/resources/img/rocher.jpg";
    private static final EnvironnementView instance = new EnvironnementView();

    /**
     * Creates new form EnrinonnementView
     */
    private EnvironnementView() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        panelBackground.setLayout(new GridLayout(environnement.getNbLine(), environnement.getNbColumn(), 5, 5));
        this.setVisible(true);
    }

    public static EnvironnementView getInstance() {
        return instance;
    }

    public List<MyButton> getButtons() {
        return buttons;
    }

    public void setButtons(List<MyButton> buttons) {
        this.buttons = buttons;
    }

    public void initialize()  {
        MyButton button;
        for (int i = 0; i < environnement.getNbLine(); i++) {
            for (int j = 0; j < environnement.getNbLine(); j++) {
                Cellule cellule = environnement.getCellules()[i][j];
                button = new MyButton(cellule);
                button.setPreferredSize(dimension);
                button.setBorder(new EtchedBorder());
                this.panelBackground.add(button);
                buttons.add(button);
                button.displayCellule();
            }
        }
        this.validate();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 729, Short.MAX_VALUE)
        );
        panelBackgroundLayout.setVerticalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel panelBackground;
    // End of variables declaration//GEN-END:variables

}
